version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 5
    labels: [dependencies, python]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:45"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 5
    labels: [dependencies, github-actions]

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 5
    labels: [dependencies, container]

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels: [dependencies, terraform]
