global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    platform: huawei-cloud-aiops
    environment: local

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: catalog-api
    metrics_path: /metrics
    static_configs:
      - targets: ["catalog-api:8001"]
        labels: {service: catalog-api}

  - job_name: orders-api
    metrics_path: /metrics
    static_configs:
      - targets: ["orders-api:8002"]
        labels: {service: orders-api}

  - job_name: payments-api
    metrics_path: /metrics
    static_configs:
      - targets: ["payments-api:8003"]
        labels: {service: payments-api}

  - job_name: aiops-api
    metrics_path: /metrics
    static_configs:
      - targets: ["aiops-api:8004"]
        labels: {service: aiops-api}

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]
