from prometheus_client import Counter, Gauge, Histogram

HTTP_REQUESTS = Counter(
    "http_server_requests_total",
    "Total HTTP requests handled by the platform services.",
    ["service", "method", "route", "status"],
)

HTTP_DURATION = Histogram(
    "http_server_request_duration_seconds",
    "HTTP request duration in seconds.",
    ["service", "method", "route"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5),
)

DEPENDENCY_REQUESTS = Counter(
    "dependency_requests_total",
    "Outbound dependency requests.",
    ["service", "dependency", "operation", "outcome"],
)

BUSINESS_EVENTS = Counter(
    "business_events_total",
    "Domain events generated by the demo workloads.",
    ["service", "event", "outcome"],
)

ACTIVE_INCIDENTS = Gauge(
    "aiops_active_incidents",
    "Number of incidents currently considered active.",
    ["severity"],
)

AUTOMATION_ACTIONS = Counter(
    "aiops_automation_actions_total",
    "Incident automation decisions.",
    ["action", "mode", "outcome"],
)

ANOMALY_SCORE = Gauge(
    "aiops_anomaly_score",
    "Latest normalized anomaly score.",
    ["service", "metric"],
)
