apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccounts.yaml
  - incident-responder-rbac.yaml
  - deployments.yaml
  - services.yaml
  - autoscaling.yaml
  - pod-disruption-budgets.yaml
  - network-policies.yaml
