apiVersion: v1
kind: Namespace
metadata:
  name: huawei-aiops
  labels:
    app.kubernetes.io/part-of: huawei-aiops-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
