apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: huawei-aiops
  labels: {app.kubernetes.io/name: catalog-api}
spec:
  selector: {app.kubernetes.io/name: catalog-api}
  ports:
    - {name: http, port: 8001, targetPort: http}
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: huawei-aiops
  labels: {app.kubernetes.io/name: orders-api}
spec:
  selector: {app.kubernetes.io/name: orders-api}
  ports:
    - {name: http, port: 8002, targetPort: http}
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: huawei-aiops
  labels: {app.kubernetes.io/name: payments-api}
spec:
  selector: {app.kubernetes.io/name: payments-api}
  ports:
    - {name: http, port: 8003, targetPort: http}
---
apiVersion: v1
kind: Service
metadata:
  name: aiops-api
  namespace: huawei-aiops
  labels: {app.kubernetes.io/name: aiops-api}
spec:
  selector: {app.kubernetes.io/name: aiops-api}
  ports:
    - {name: http, port: 8004, targetPort: http}
