apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload
  labels:
    {{- include "huawei-aiops.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-responder
  labels:
    {{- include "huawei-aiops.commonLabels" . | nindent 4 }}
automountServiceAccountToken: true
